//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by VoicePrompt.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_VOICEPROMPT_DIALOG          102
#define IDS_STRING_MOUSECLEW            102
#define IDS_STRING_ENUMNAME             103
#define IDS_STRING_FILENAME             104
#define IDS_STRING_LISTCTRL_ENUM        105
#define IDS_STRING_LISTCTRL_FILENAME    106
#define IDS_STRING_FILEEXIST            107
#define IDS_STRING_MENUADD              108
#define IDS_STRING_MENUMODIFY           109
#define IDS_STRING_MENUDELETE           110
#define IDS_STRING_SELECTFILE           111
#define IDS_STRING_FILTER               112
#define IDS_STRING_DEFAULT_EXTENTNAME   113
#define IDS_STRING_CLEW                 114
#define IDS_STRING_FINDSOURFILEFAIL     115
#define IDS_STRING_INPUTENUM            116
#define IDS_STRING_INPUTFILENAME        117
#define IDS_STRING_FILESIZE             118
#define IDS_STRING_LANGUAGE3            119
#define IDS_STRING_LANGUAGE1            120
#define IDS_STRING_FILTER_INI           121
#define IDS_STRING_CONFIG               122
#define IDS_STRING_SELECTFOLD           123
#define IDS_STRING_INPUTPATH            124
#define IDS_STRING_FINDSOURFOLDFAIL     125
#define IDS_STRING_CONFIRMLANFILE       126
#define IDS_STRING_CLEWSELLAN           127
#define IDR_MAINFRAME                   128
#define IDS_STRING_LANSEQUENCE2         128
#define IDD_DIALOG_OPTION               129
#define IDS_STRING_LANSEQUENCE11        129
#define IDD_DIALOG_ENUMINFO             130
#define IDS_STRING_LANSEQUENCE12        130
#define IDB_BITMAP_DELETE               131
#define IDS_STRING_CHANGEFILENAME       131
#define IDB_BITMAP_NEW                  132
#define IDS_STRING_YES                  132
#define IDS_STRING_OPTIONCLEW           133
#define IDD_DIALOG_FILESIZECOUNT        134
#define IDS_STRING_ENUMEXIST            134
#define IDD_DIALOG_OUTFILES             135
#define IDS_STRING1_SELECT3LANGUAGE     135
#define IDB_BITMAP_UP                   136
#define IDS_STRING_NO                   136
#define IDB_BITMAP_BELOW                137
#define IDS_STRING_ENTERLANGUAGE        137
#define IDB_BITMAP_TOP                  138
#define IDS_STRING_LANGUAGEEXIST        138
#define IDB_BITMAP_DOWN                 139
#define IDS_STRING_CHECKCOMPLETE        139
#define IDS_STRING_FILESIZEINFO         140
#define IDD_DIALOG_BATCHOUTPUTFILES     140
#define IDS_STRING_DELETELANGUAGE       141
#define IDD_DIALOG_BATCHADD             141
#define IDS_STRING_CANNOTFINDFILE       142
#define IDD_DIALOG_BATCH_OUTPUT_OPTION  142
#define IDS_STRING_ANDSTRING            143
#define IDS_STRING_SINGLELANINFO        144
#define IDS_STRING_SINGLELANACCOUNT     145
#define IDS_STRING_LANGUAGEACCOUNT      146
#define IDS_STRING_CANNOTWRITEFILE      147
#define IDS_STRING_CANNOTWRITEFILES     148
#define IDS_STRING_OUTPUTCOMPLETE       149
#define IDS_STRING_CANNOTREADFILE       150
#define IDS_STRING_CANNOTOPENFOLD       151
#define IDS_STRING_LANGUAGECOUNT        152
#define IDS_STRING_SELECTLANGUAGE       153
#define IDS_STRING_BATCH_OUTPUTLAN      154
#define IDS_STRING_BATCH_SELLANFILE     155
#define IDS_STRING_BATCH_OUTFOLD        156
#define IDS_STRING_BATCH_ADD_DIALOG     157
#define IDS_STRING_AND                  158
#define IDS_STRING_BATCH_MODIFY         159
#define IDS_STRING_BATCHDELETE          160
#define IDS_STRING_BATCHINVALIDDATA     161
#define IDS_STRING_CANNOTCHECKOUTFILE   162
#define IDS_STRING_CLEW_SETFOLD         163
#define IDS_STRING_BATCHOUTPUT_PACKCLEW 164
#define IDS_STRING_OUTPUTCLEW           165
#define IDS_STRING_LANGUAGESIZEINFO     166
#define IDS_STRING_BATCHOUTPUTRESUTL    167
#define IDS_STRING_BATCH_SIZE_INFO      168
#define IDS_STRING_CREATE_PLACEFILE     169
#define IDS_STRING_ADDENUMCLEW          170
#define IDS_STRING_AUTOCHANGEFILENAME   171
#define IDC_LIST_LANGUAGE               1000
#define IDC_BUTTON_COUNTLANGUAGESSIZE   1001
#define IDC_BUTTON_SELECTPAHT           1001
#define IDC_BUTTON_COPY                 1001
#define IDC_BUTTON_CLEARALL             1002
#define IDC_BUTTON_ADDLANGUAGE          1003
#define IDC_BUTTON_DELETELANGUAGE       1004
#define IDC_LIST_ENUMINFO               1006
#define IDC_BUTTON_OPTION               1007
#define IDC_BUTTON_CREATECONFIG         1008
#define IDC_EDIT_LANGUAGE               1009
#define IDC_COMBO_SELECTPATH            1017
#define IDC_BUTTON_OUTPUTFILES          1019
#define IDC_BUTTON_LANGUAGEUP           1020
#define IDC_BUTTON_LANGUAGEDOWN         1021
#define IDC_BUTTON_PATH                 1022
#define IDC_COMBO_ENUM                  1023
#define IDC_COMBO_FILENAME              1024
#define IDC_EDIT_DATA_FILENAME          1025
#define IDC_EDIT_DATA_VARIABLE          1026
#define IDC_EDIT_DATA_PREPARE_CONTENT   1027
#define IDC_EDIT_POS_FILENAME           1028
#define IDC_EDIT_POS_VARIABLE           1029
#define IDC_EDIT_POS_PREPARE_CONTENT    1030
#define IDC_STATIC_ALLSIZE              1031
#define IDC_EDIT_LANGUAGEPACKINFORMATION 1032
#define IDC_PROGRESS_OUTPUT             1034
#define IDC_BUTTON_MOVETOP              1035
#define IDC_BUTTON_MOVEBELOW            1036
#define IDC_BUTTON_RESET                1037
#define IDC_BUTTON_CHECKFILE            1038
#define IDC_RADIO_ALLFILES              1039
#define IDC_RADIO_NEEDFILES             1040
#define IDC_STATIC_LANGUAGEINFO         1041
#define IDC_BUTTON_COUNTALLLANGUAGES    1042
#define IDC_BUTTON_COUNTSILENT          1043
#define IDC_BUTTON_BATCHOUTPUTFILES     1044
#define IDC_LIST_BATCHLANGUAGE          1045
#define IDC_BUTTON_BATCH_TOP            1046
#define IDC_BUTTON_BATCH_UP             1047
#define IDC_BUTTON_BATCHDOWN            1048
#define IDC_BUTTON_BATCHBELOW           1049
#define IDC_LIST_BATCHOUTPUT            1050
#define IDC_BUTTON_ADDBATCHITEM         1051
#define IDC_BUTTON_DELETE               1052
#define IDC_BUTTON_BATCHOUTPUT          1053
#define IDC_COMBO_SELECTFILE            1055
#define IDC_BUTTON_BATCHSELFILE         1056
#define IDC_BUTTON_SELECTFOLD           1059
#define IDC_STATIC_LANGUAGES            1060
#define IDC_EDIT_CHOOSELANGUAGE_FOLD    1063
#define IDC_EDIT_BATCH_OUTPUTROOT_FOLD  1064
#define IDC_BUTTON_CHOOSEFOLD           1065
#define IDC_BUTTON_LANGUAGEROOT_FOLD    1066
#define IDC_PROGRESS_BATCHOUTPUTFILES   1068
#define IDC_STATIC_OUTPUTFILESCOUNT     1069
#define IDC_BUTTON1                     1071
#define IDC_BUTTON_TEST                 1071

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        144
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1072
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
